import React, { useState, useRef, useCallback, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Upload,
  ScrollText,
  Mail,
  X,
  Github,
  Sparkles,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Download,
  FileCode,
  ArrowLeft,
  Server,
  ServerCrash,
  Wifi,
  WifiOff,
  Info,
} from 'lucide-react';

import { TextRoll } from '@/components/core/text-roll';
import { Spotlight } from '@/components/core/spotlight';
import { Dock, DockIcon, DockItem, DockLabel } from '@/components/core/dock';

// ─── Types ─────────────────────────────────────────────────────────────────

interface IngredientRow {
  name: string;
  risk: 'safe' | 'caution' | 'hazard';
  role: string;
  confidence: string;
}

interface AnalysisResult {
  productName: string;
  safetyScore: number;
  riskLabel: string;
  ingredientCount: number;
  researchConfidence: number;
  summary: string;
  warnings: string[];
  ingredients: IngredientRow[];
  report: string;
  sampleMode: boolean;
}

interface ResearchResult {
  purpose?: string;
  human_safety_status?: string;
  evidence_based_safety_assessment?: string;
  confidence_score?: string;
}

interface ApiResponse {
  success: boolean;
  product_name: string;
  safety_score: number | null;
  risk_label: string | null;
  ocr_text: string;
  ingredients: string[];
  research_results: Record<string, ResearchResult>;
  safety_analysis: {
    summary?: string;
    warnings?: string[];
    recommendations?: string[];
    overall_score?: string | number;
  };
  markdown_report: string;
  json_report: Record<string, unknown>;
  report_md_path: string;
  report_json_path: string;
  source_image_path?: string;
  sample_image_used?: boolean;
}

interface BackendHealth {
  loading: boolean;
  reachable: boolean;
  status?: 'ok' | 'degraded';
  gemini?: boolean;
  tavily?: boolean;
  message?: string;
  lastChecked?: number;
  port?: number;
  host?: string;
}

type ModalType = 'about' | 'contact' | null;
type PipelineStep = 0 | 1 | 2 | 3 | 4 | 5 | 6;

// ─── Backend response → UI mapping ─────────────────────────────────────────

const riskFromStatus = (status: string): IngredientRow['risk'] => {
  const s = (status ?? '').toLowerCase();
  if (/(not recommended|danger|high risk)/.test(s)) return 'hazard';
  if (/(caution|conditions|insufficient|medium)/.test(s)) return 'caution';
  return 'safe';
};

const mapResult = (data: ApiResponse): AnalysisResult => {
  const safety = data.safety_analysis ?? {};
  const research = data.research_results ?? {};

  const ingredients: IngredientRow[] = (data.ingredients ?? []).map((name: string) => {
    const rep = research[name] ?? {};
    return {
      name,
      role: rep.purpose || '—',
      risk: riskFromStatus(rep.human_safety_status ?? rep.evidence_based_safety_assessment ?? ''),
      confidence: rep.confidence_score || 'Unknown',
    };
  });

  const confValues: Record<string, number> = { High: 100, Medium: 70, Low: 40 };
  const confs = ingredients.map((i) => confValues[i.confidence] ?? 0);
  const researchConfidence = confs.length
    ? Math.round(confs.reduce((a, b) => a + b, 0) / confs.length)
    : 0;

  const hasIngredients = ingredients.length > 0;

  // Prefer numeric safety_score from pipeline (report node). Fallback to
  // safety_analysis.overall_score if that's what the LLM returned.
  let score: number;
  if (typeof data.safety_score === 'number') {
    score = data.safety_score;
  } else if (typeof safety.overall_score === 'number') {
    score = safety.overall_score;
  } else if (typeof safety.overall_score === 'string') {
    const m = /\b(100|[1-9]?\d)\b/.exec(safety.overall_score);
    score = m ? Number(m[1]) : 0;
  } else {
    score = 0;
  }

  let riskLabel: string;
  if (hasIngredients) {
    riskLabel =
      data.risk_label ||
      (score >= 80 ? 'Safe / Low Risk' : score >= 50 ? 'Caution / Medium Risk' : 'Danger / High Risk');
  } else {
    riskLabel = 'No Ingredients Detected';
  }

  const summary = hasIngredients
    ? safety.summary || 'No summary available.'
    : 'No ingredients were detected in this image. Try a clearer, higher-resolution product label.';

  return {
    productName: data.product_name || 'Analyzed Product',
    safetyScore: score,
    riskLabel,
    ingredientCount: ingredients.length,
    researchConfidence,
    summary,
    warnings: hasIngredients ? safety.warnings || [] : [],
    ingredients,
    report: data.markdown_report || 'No report was generated by the pipeline.',
    sampleMode: !!data.sample_image_used,
  };
};

// ─── Backend Configuration ────────────────────────────────────────────────

// Use environment variable if set (for production deployments)
// Otherwise fallback to relative path (/api) which works when frontend/backend are on same domain
// Note: __BACKEND_URL__ is replaced at build time by Vite's define option
const getApiUrl = (endpoint: string) => {
  // @ts-ignore - __BACKEND_URL__ is defined in vite.config.ts at build time
  const backendUrl = __BACKEND_URL__ || '';
  
  // If we have a full URL (production), use it
  if (backendUrl && !backendUrl.startsWith('http')) {
    // It's a relative path, append endpoint
    return `${backendUrl}${endpoint}`;
  }
  // If it's a full URL, ensure we don't double-slash join
  return backendUrl ? `${backendUrl.replace(/\/$/, '')}${endpoint}` : endpoint;
};

const PIPELINE_STEPS = [
  { id: 1, label: 'Upload', runMsg: 'Sending image…', doneMsg: '✓ Received' },
  { id: 2, label: 'OCR', runMsg: 'Extracting text…', doneMsg: '✓ Extracted' },
  { id: 3, label: 'INCI', runMsg: 'Normalising…', doneMsg: '✓ Mapped' },
  { id: 4, label: 'Research', runMsg: 'Web search…', doneMsg: '✓ Researched' },
  { id: 5, label: 'Safety', runMsg: 'Scoring risks…', doneMsg: '✓ Scored' },
  { id: 6, label: 'Report', runMsg: 'Generating report…', doneMsg: '✓ Complete' },
];

// ─── Risk badge ────────────────────────────────────────────────────────────

const RiskBadge: React.FC<{ risk: IngredientRow['risk'] }> = ({ risk }) => {
  const cls = {
    safe: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/25',
    caution: 'bg-amber-500/10 text-amber-400 border-amber-500/25',
    hazard: 'bg-rose-500/10 text-rose-400 border-rose-500/25',
  }[risk];
  return (
    <span className={`text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded-full border ${cls}`}>
      {risk}
    </span>
  );
};

// ─── Backend status pill ───────────────────────────────────────────────────

const BackendStatus: React.FC<{ health: BackendHealth; onRetry: () => void }> = ({ health, onRetry }) => {
  const portSuffix = typeof health.port === 'number' ? ` :${health.port}` : '';

  if (health.loading) {
    return (
      <div className="flex items-center gap-2 rounded-full border border-white/8 bg-white/5 px-3 py-1.5">
        <motion.span
          animate={{ opacity: [0.3, 1, 0.3] }}
          transition={{ duration: 1.2, repeat: Infinity }}
          className="w-2 h-2 rounded-full bg-amber-400"
        />
        <span className="text-[10px] font-mono text-zinc-400 uppercase tracking-widest">
          Connecting to backend…
        </span>
      </div>
    );
  }

  if (!health.reachable) {
    return (
      <button
        onClick={onRetry}
        title="Retry backend connection"
        className="group flex items-center gap-2 rounded-full border border-rose-500/30 bg-rose-500/10 hover:bg-rose-500/15 px-3 py-1.5 transition-colors"
      >
        <ServerCrash className="w-3 h-3 text-rose-400" />
        <span className="text-[10px] font-mono text-rose-300 uppercase tracking-widest">
          Backend offline
        </span>
        <WifiOff className="w-3 h-3 text-rose-400 group-hover:translate-x-0.5 transition-transform" />
      </button>
    );
  }

  if (health.status === 'degraded' || !health.gemini) {
    return (
      <button
        onClick={onRetry}
        title="Retry backend health check"
        className="group flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 hover:bg-amber-500/15 px-3 py-1.5 transition-colors"
      >
        <Server className="w-3 h-3 text-amber-400" />
        <span className="text-[10px] font-mono text-amber-300 uppercase tracking-widest">
          Backend degraded — missing Gemini key{portSuffix}
        </span>
        <AlertTriangle className="w-3 h-3 text-amber-400" />
      </button>
    );
  }

  return (
    <button
      onClick={onRetry}
      title="Re-check backend health"
      className="group flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 hover:bg-emerald-500/15 px-3 py-1.5 transition-colors"
    >
      <Server className="w-3 h-3 text-emerald-400" />
      <span className="text-[10px] font-mono text-emerald-300 uppercase tracking-widest">
        Backend connected{portSuffix}
      </span>
      <Wifi className="w-3 h-3 text-emerald-400 group-hover:scale-110 transition-transform" />
    </button>
  );
};

// ─── Modal ────────────────────────────────────────────────────────────────

const Modal: React.FC<{ type: ModalType; onClose: () => void }> = ({ type, onClose }) => (
  <AnimatePresence>
    {type && (
      <>
        <motion.div
          className="fixed inset-0 z-50 bg-black/60 backdrop-blur-md"
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
          onClick={onClose}
        />
        <motion.div
          className="fixed z-50 left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-sm bg-zinc-950 border border-white/10 rounded-3xl p-8 shadow-2xl"
          initial={{ opacity: 0, scale: 0.9, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.9, y: 10 }}
          transition={{ type: 'spring', stiffness: 340, damping: 30 }}
        >
          <button
            onClick={onClose}
            className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-white/8 text-zinc-500 hover:text-white transition-colors"
          >
            <X className="w-4 h-4" />
          </button>

          {type === 'about' ? (
            <div className="text-center space-y-4">
              <div className="w-14 h-14 rounded-2xl bg-white/8 border border-white/10 flex items-center justify-center mx-auto text-2xl">
                🧪
              </div>
              <div>
                <h3 className="text-lg font-bold text-white uppercase tracking-tight">IngredientSight AI</h3>
                <span className="text-[11px] font-mono text-zinc-500 block mt-1">AI Product Safety Platform</span>
              </div>
              <div className="space-y-2 text-sm text-zinc-400 text-center">
                <p className="bg-white/5 border border-white/8 rounded-xl px-4 py-2 font-mono text-xs">Version 1.0.0 — LangGraph v1.0</p>
                <p className="text-base">Made with <span className="text-red-400 text-lg">❤️</span> for safer cosmetics.</p>
              </div>
              <div className="text-[10px] font-mono text-zinc-600 pt-2">
                Powered by LangGraph · LangChain · Google Gemini
              </div>
            </div>
          ) : (
            <div className="space-y-5">
              <div>
                <h3 className="text-lg font-bold text-white uppercase tracking-tight">Contact Info</h3>
                <span className="text-[11px] font-mono text-zinc-500">Reach out or explore the project</span>
              </div>

              <div className="space-y-3">
                <div className="flex items-center gap-3 bg-white/5 border border-white/8 rounded-2xl p-4">
                  <div className="w-9 h-9 rounded-xl bg-white/8 flex items-center justify-center flex-shrink-0">
                    <Mail className="w-4 h-4 text-zinc-300" />
                  </div>
                  <div>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase block">Email</span>
                    <span className="text-sm text-white font-mono">asd@gmail.com</span>
                  </div>
                </div>

                <a
                  href="https://github.com/pritamdey0/IngredientSight-AI.git"
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-3 bg-white/5 border border-white/8 hover:border-white/20 rounded-2xl p-4 transition-colors group"
                >
                  <div className="w-9 h-9 rounded-xl bg-white/8 flex items-center justify-center flex-shrink-0">
                    <Github className="w-4 h-4 text-zinc-300" />
                  </div>
                  <div>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase block">GitHub Repository</span>
                    <span className="text-xs text-white font-mono group-hover:underline">IngredientSight-AI</span>
                  </div>
                </a>
              </div>
            </div>
          )}
        </motion.div>
      </>
    )}
  </AnimatePresence>
);

// ─── Dashboard ────────────────────────────────────────────────────────────

interface DashboardProps {
  onBackToLanding: () => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ onBackToLanding }) => {
  const [modal, setModal] = useState<ModalType>(null);
  const [dragOver, setDragOver] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [pipelineStep, setPipelineStep] = useState<PipelineStep>(0);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [productInput, setProductInput] = useState('');
  const [health, setHealth] = useState<BackendHealth>({
    loading: true,
    reachable: false,
  });

  const fileRef = useRef<HTMLInputElement>(null);
  const tickRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const abortRef = useRef<AbortController | null>(null);

  const checkHealth = useCallback(async () => {
    setHealth((h) => ({ ...h, loading: true }));
    const controller = new AbortController();
    const to = setTimeout(() => controller.abort(), 6000);
    try {
      const res = await fetch(getApiUrl('/api/health'), {
        method: 'GET',
        signal: controller.signal,
        headers: { Accept: 'application/json' },
      });
      clearTimeout(to);

      if (res.ok) {
        const data = (await res.json()) as BackendHealth & {
          gemini_configured?: boolean;
          tavily_configured?: boolean;
          port?: number;
          host?: string;
        };
        setHealth({
          loading: false,
          reachable: true,
          status: (data.status as 'ok' | 'degraded') || 'ok',
          gemini: typeof data.gemini_configured === 'boolean' ? data.gemini_configured : data.gemini,
          tavily: typeof data.tavily_configured === 'boolean' ? data.tavily_configured : data.tavily,
          port: typeof data.port === 'number' ? data.port : undefined,
          host: typeof data.host === 'string' ? data.host : undefined,
          lastChecked: Date.now(),
        });
      } else {
        setHealth({
          loading: false,
          reachable: false,
          message: `Health check returned status ${res.status}`,
          lastChecked: Date.now(),
        });
      }
    } catch (err) {
      clearTimeout(to);
      const msg =
        (err as Error)?.name === 'AbortError'
          ? 'Connection timed out'
          : (err as Error)?.message || 'Network error';
      setHealth({
        loading: false,
        reachable: false,
        message: msg,
        lastChecked: Date.now(),
      });
    }
  }, []);

  useEffect(() => {
    checkHealth();
  }, [checkHealth]);

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const stopTicker = useCallback(() => {
    if (tickRef.current) {
      clearInterval(tickRef.current);
      tickRef.current = null;
    }
  }, []);

  useEffect(() => {
    return () => {
      abortRef.current?.abort();
      stopTicker();
    };
  }, [stopTicker]);

  const analyze = useCallback(async (formData: FormData) => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    stopTicker();
    setError(null);
    setResult(null);
    setIsAnalyzing(true);
    setPipelineStep(1);

    let step: PipelineStep = 1;
    tickRef.current = setInterval(() => {
      if (step < PIPELINE_STEPS.length) {
        step = (step + 1) as PipelineStep;
        setPipelineStep(step);
      }
    }, 900);

    try {
      const hasFile = formData.has('file');
      if (!hasFile && !formData.get('product_name')) {
        throw new Error(
          'Please upload a product-label image, or at minimum type a product name. '
          + 'Image upload is required for a real analysis.',
        );
      }

      const res = await fetch(getApiUrl('/api/analyze'), {
        method: 'POST',
        body: formData,
        signal: controller.signal,
      });

      if (!res.ok) {
        let detail = `Server error (${res.status})`;
        try {
          const body = await res.json();
          if (body?.detail) {
            detail = typeof body.detail === 'string' ? body.detail : JSON.stringify(body.detail);
          }
        } catch {
          /* non-JSON error body */
        }
        throw new Error(detail);
      }

      const data = (await res.json()) as ApiResponse;
      if (!data.success) {
        throw new Error('Backend reported an unsuccessful analysis.');
      }
      setResult(mapResult(data));
    } catch (err) {
      if ((err as Error)?.name === 'AbortError') return;
      const baseMsg =
        err instanceof Error && err.message
          ? err.message
          : 'Could not reach the IngredientSight AI backend.';

      let hint = '';
      if (/(401|unauthenticated|credential|api[_\s-]?key)/i.test(baseMsg)) {
        hint = 'Check that GOOGLE_API_KEY (or GEMINI_API_KEY) is set to a valid key in your .env file, then restart the backend server.';
      } else if (/(503|pipeline.*not compiled|langgraph pipeline)/i.test(baseMsg)) {
        hint = 'The backend started but could not compile the LangGraph pipeline. Check the server terminal for Python import errors — ensure all dependencies from requirements.txt are installed (fastapi, uvicorn, pillow, google-genai, langgraph, etc.).';
      } else if (/(failed to fetch|networkerror|connection refused|econnrefused|backend offline|timed out)/i.test(baseMsg + ' ' + (health.message || ''))) {
        // @ts-ignore - __BACKEND_URL__ is defined in vite.config.ts at build time
        const backendUrl = __BACKEND_URL__ || '';
        const displayUrl = backendUrl ? backendUrl.replace(/https?:\/\//, '').replace(/\/$/, '') : 'localhost:8000';
        hint = `
          The backend at ${displayUrl} is not reachable.\n\n`
          + `If you're using Vercel + Render:\n`  
          + `  1. Make sure you set VITE_API_URL=https://your-render-app.onrender.com in Vercel dashboard\n`  
          + `  2. Verify your Render backend is running and accessible\n\n`
          + `If running locally:\n`  
          + `  Start the backend with: python server.py (in a separate terminal)`;
      } else if (health.reachable && !health.gemini) {
        hint = 'Backend replied but your Gemini API key is missing or invalid. Re-check .env next to server.py and restart the Python server.';
      } else {
        // @ts-ignore - __BACKEND_URL__ is defined in vite.config.ts at build time
        const backendUrl = __BACKEND_URL__ || '';
        const displayUrl = backendUrl ? backendUrl.replace(/https?:\/\//, '').replace(/\/$/, '') : 'localhost:8000';
        hint = `Make sure the FastAPI server is running on ${displayUrl}. Command: python server.py`;
      }

      setError(`${baseMsg} — ${hint}`);
    } finally {
      if (abortRef.current === controller) {
        abortRef.current = null;
        stopTicker();
        setIsAnalyzing(false);
        setPipelineStep(0);
      }
    }
  }, [stopTicker, health.reachable, health.gemini, health.message]);

  const handleFile = (file: File) => {
    const fd = new FormData();
    fd.append('file', file);
    analyze(fd);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer.files?.[0]) handleFile(e.dataTransfer.files[0]);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const val = productInput.trim();
    if (!val) return;
    setProductInput('');
    const fd = new FormData();
    fd.append('product_name', val);
    analyze(fd);
  };

  const scoreColor = result
    ? result.safetyScore >= 80 ? 'text-emerald-400' : result.safetyScore >= 60 ? 'text-amber-400' : 'text-rose-400'
    : '';

  return (
    <div className="relative min-h-screen bg-black text-white font-['Inter_Tight',sans-serif] font-medium tracking-[-0.04em] flex flex-col overflow-x-hidden">

      <div className="pointer-events-none fixed inset-0 z-0">
        <svg className="absolute inset-0 h-full w-full opacity-20">
          <defs>
            <pattern id="dash-grid" width="40" height="40" patternUnits="userSpaceOnUse">
              <path d="M0 20H20M20 20V0M20 20H40M20 20V40" stroke="white" strokeOpacity="0.15" strokeWidth="0.5" />
              <rect x="19" y="19" width="2" height="2" fill="white" fillOpacity="0.12" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#dash-grid)" />
        </svg>

        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[340px] bg-[radial-gradient(ellipse_at_top,rgba(59,130,246,0.18)_0%,transparent_70%)]" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,transparent_50%,rgba(0,0,0,0.6)_100%)]" />
      </div>

      <div className="relative z-10 flex flex-wrap items-center justify-between gap-2 px-6 pt-5">
        <button
          onClick={onBackToLanding}
          className="flex items-center gap-2 text-[11px] font-mono text-zinc-600 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Back
        </button>
      </div>

      <div className="relative z-10 flex flex-col items-center pt-6 pb-6 px-6 text-center">
        <motion.span
          initial={{ opacity: 0, y: -12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-[10px] font-mono text-zinc-500 uppercase tracking-[0.2em] mb-4 block"
        >
          AI-Powered Cosmetic Safety Platform
        </motion.span>

        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-[-0.05em] leading-none">
          <TextRoll className="text-white">IngredientSight AI</TextRoll>
        </h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1, duration: 0.6 }}
          className="mt-4 text-sm text-zinc-500 font-mono tracking-normal max-w-md"
        >
          Upload a product label or enter a product name — the AI does the rest.
        </motion.p>
      </div>

      <main className="relative z-10 flex-1 w-full max-w-4xl mx-auto px-5 pb-36 space-y-6">

        <AnimatePresence>
          {!health.loading && !health.reachable && (
            <motion.section
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -16 }}
              className="relative rounded-3xl border border-rose-500/30 bg-rose-500/5 overflow-hidden"
            >
              <div className="relative z-10 flex flex-col sm:flex-row sm:items-start gap-4 p-5 sm:p-6">
                <div className="flex-shrink-0 w-10 h-10 rounded-2xl bg-rose-500/15 border border-rose-500/30 flex items-center justify-center">
                  <ServerCrash className="w-5 h-5 text-rose-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-mono text-rose-300 uppercase tracking-widest mb-1">
                    Backend not connected
                  </p>
                  <p className="text-sm text-zinc-200 leading-relaxed">
                    The dashboard can&apos;t reach the FastAPI backend on{' '}
                    <code className="px-1.5 py-0.5 rounded bg-white/5 border border-white/10 text-rose-200 font-mono text-xs">
                      {(() => {
                        // @ts-ignore - __BACKEND_URL__ is defined in vite.config.ts at build time
                        const backendUrl = __BACKEND_URL__ || '';
                        return backendUrl ? backendUrl.replace(/https?:\/\//, '').replace(/\/$/, '') : 'localhost:8000';
                      })()}
                    </code>
                    . Uploads will fail until the Python server is running.
                  </p>
                  <div className="mt-3 rounded-2xl border border-white/10 bg-black/40 p-4 font-mono text-xs text-zinc-300 leading-relaxed">
                    <p className="mb-1 text-zinc-500"># Install Python dependencies (once)</p>
                    <p className="text-emerald-300 mb-3">pip install -r requirements.txt</p>
                    <p className="mb-1 text-zinc-500"># Then start the backend (leave this running)</p>
                    <p className="text-emerald-300">python server.py</p>
                  </div>
                  <button
                    onClick={checkHealth}
                    className="mt-4 inline-flex items-center gap-2 rounded-full bg-white text-black text-xs font-bold uppercase tracking-widest px-4 py-2 hover:bg-zinc-100 transition-colors"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    Re-check connection
                  </button>
                </div>
              </div>
            </motion.section>
          )}
        </AnimatePresence>

        <motion.section
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
          className="relative rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden"
        >
          <Spotlight
            className="from-blue-700 via-blue-500 to-transparent blur-2xl"
            size={260}
          />

          <div className="relative z-10 p-6 sm:p-8">
            <div className="flex items-center gap-2 mb-6">
              <Upload className="w-4 h-4 text-zinc-400" />
              <span className="text-[11px] font-mono text-zinc-400 uppercase tracking-widest">Upload &amp; Analyze</span>
            </div>

            <div className="flex justify-center w-full">
              <motion.div
                onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
                onDragLeave={() => setDragOver(false)}
                onDrop={handleDrop}
                onClick={() => fileRef.current?.click()}
                animate={{ borderColor: dragOver ? 'rgba(255,255,255,0.35)' : 'rgba(255,255,255,0.08)' }}
                className="relative cursor-pointer rounded-2xl border border-white/8 bg-white/5 p-8 flex flex-col items-center justify-center text-center gap-3 group hover:border-white/20 hover:bg-white/[0.07] transition-colors w-full max-w-lg"
              >
                <input
                  ref={fileRef}
                  type="file"
                  accept="image/png,image/jpeg,image/jpg,image/webp,image/gif"
                  onChange={(e) => { if (e.target.files?.[0]) handleFile(e.target.files[0]); }}
                  className="hidden"
                />

                <div className="w-12 h-12 rounded-2xl bg-white/8 border border-white/10 flex items-center justify-center group-hover:scale-110 transition-transform text-white">
                  <Upload className="w-5 h-5" />
                </div>

                <div>
                  <p className="text-sm font-semibold text-white uppercase tracking-tight">Drop Image Here</p>
                  <p className="text-[11px] text-zinc-600 font-mono mt-1 tracking-normal">or click to browse · PNG · JPG · JPEG</p>
                </div>

                <p className="text-[10px] font-mono text-zinc-700 max-w-[14rem] leading-snug">
                  For best OCR results use a well-lit, in-focus photo of the ingredient list panel.
                </p>

                {dragOver && (
                  <motion.div
                    initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                    className="absolute inset-0 rounded-2xl bg-blue-500/10 border-2 border-blue-400/40 flex items-center justify-center"
                  >
                    <span className="text-sm font-bold text-blue-300">Release to analyze</span>
                  </motion.div>
                )}
              </motion.div>
            </div>

            <AnimatePresence>
              {error && (
                <motion.div
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  className="mt-5 rounded-2xl border border-rose-500/25 bg-rose-500/8 p-4 flex items-start gap-3"
                >
                  <AlertTriangle className="w-4 h-4 text-rose-400 mt-0.5 flex-shrink-0" />
                  <div className="text-xs text-rose-200/90 font-mono tracking-normal leading-relaxed">
                    <span className="font-bold text-rose-300 uppercase tracking-widest block mb-1">Analysis failed</span>
                    <div className="whitespace-pre-wrap">{error}</div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <AnimatePresence>
              {isAnalyzing && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-5 overflow-hidden"
                >
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest">Multi-agent pipeline</span>
                    <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-ping" />
                  </div>
                  <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
                    {PIPELINE_STEPS.map((pStep) => {
                      const done = pipelineStep > pStep.id;
                      const active = pipelineStep === pStep.id;
                      return (
                        <div
                          key={pStep.id}
                          className={`relative rounded-xl border p-3 overflow-hidden transition-all ${
                            done ? 'border-emerald-500/30 bg-emerald-500/5'
                                 : active ? 'border-blue-400/40 bg-blue-500/5'
                                 : 'border-white/6 bg-transparent'
                          }`}
                        >
                          <p className="text-[10px] font-bold text-white uppercase tracking-tight">{pStep.label}</p>
                          <p className="text-[9px] font-mono text-zinc-600 mt-0.5 leading-snug">
                            {done ? pStep.doneMsg : active ? pStep.runMsg : 'waiting'}
                          </p>
                          {active && (
                            <motion.div
                              className="absolute bottom-0 left-0 right-0 h-[2px] bg-blue-400"
                              initial={{ scaleX: 0 }} animate={{ scaleX: 1 }}
                              transition={{ duration: 0.8, ease: 'linear' }}
                              style={{ transformOrigin: 'left' }}
                            />
                          )}
                          {done && (
                            <CheckCircle2 className="absolute top-2 right-2 w-3 h-3 text-emerald-400" />
                          )}
                        </div>
                      );
                    })}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </motion.section>

        <AnimatePresence>
          {result && (
            <motion.section
              initial={{ opacity: 0, y: 32 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 16 }}
              transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
              className="space-y-4"
            >
              {result.sampleMode && (
                <motion.div
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="relative rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 flex items-start gap-3"
                >
                  <AlertTriangle className="w-4 h-4 text-amber-400 mt-0.5 flex-shrink-0" />
                  <div className="text-xs font-mono text-amber-200/90 leading-relaxed tracking-normal">
                    <span className="font-bold uppercase tracking-widest block mb-1 text-amber-300">
                      Demo result · sample ingredients image used
                    </span>
                    You typed a product name without uploading a label photo.
                    The AI analysed the bundled sample shampoo ingredients image instead.
                    To evaluate a real product, upload a clear photo of its ingredient list panel.
                  </div>
                </motion.div>
              )}

              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-zinc-500" />
                <span className="text-[11px] font-mono text-zinc-500 uppercase tracking-widest">Analysis Report</span>
              </div>

              <div className="relative rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden p-6 sm:p-8">
                <Spotlight className="from-emerald-700 via-emerald-500 to-transparent blur-2xl" size={240} />
                <div className="relative z-10 flex flex-col sm:flex-row sm:items-center justify-between gap-5">
                  <div>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest block mb-1">Analyzed Product</span>
                    <h2 className="text-2xl sm:text-3xl font-bold text-white uppercase tracking-tight leading-tight">
                      {result.productName}
                    </h2>
                    <p className="text-xs text-zinc-500 font-mono tracking-normal mt-2 max-w-md leading-relaxed">
                      {result.summary}
                    </p>
                  </div>
                  <div className="flex flex-col items-center sm:items-end gap-1 flex-shrink-0">
                    <span className={`text-6xl font-bold ${scoreColor}`}>{result.safetyScore}</span>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest">/ 100</span>
                    <span className={`text-xs font-bold uppercase px-3 py-1 rounded-full border mt-1 ${
                      result.safetyScore >= 80 ? 'text-emerald-400 bg-emerald-500/10 border-emerald-500/25'
                      : result.safetyScore >= 60 ? 'text-amber-400 bg-amber-500/10 border-amber-500/25'
                      : 'text-rose-400 bg-rose-500/10 border-rose-500/25'
                    }`}>{result.riskLabel}</span>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                  { label: 'Safety Score', value: `${result.safetyScore}/100`, color: scoreColor },
                  { label: 'Risk Level', value: result.riskLabel, color: 'text-white' },
                  { label: 'Ingredients', value: `${result.ingredientCount}`, color: 'text-white' },
                  { label: 'Research Confidence', value: `${result.researchConfidence}%`, color: 'text-blue-400' },
                ].map(({ label, value, color }) => (
                  <div key={label} className="rounded-2xl border border-white/8 bg-white/[0.025] p-4 flex flex-col gap-1">
                    <span className="text-[10px] font-mono text-zinc-600 uppercase tracking-widest">{label}</span>
                    <span className={`text-xl font-bold ${color} break-words`}>{value}</span>
                  </div>
                ))}
              </div>

              {result.warnings.length > 0 && (
                <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5">
                  <div className="flex items-center gap-2 mb-3">
                    <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
                    <span className="text-[10px] font-mono text-amber-400 uppercase tracking-widest">Warnings</span>
                  </div>
                  <ul className="space-y-2">
                    {result.warnings.map((w, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-xs text-zinc-300 leading-relaxed font-mono tracking-normal">
                        <span className="w-1.5 h-1.5 bg-amber-400 rounded-full mt-1.5 flex-shrink-0" />
                        {w}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden">
                <div className="px-6 py-4 border-b border-white/6">
                  <h3 className="text-sm font-bold text-white uppercase tracking-tight">Ingredient Breakdown</h3>
                  <p className="text-[10px] font-mono text-zinc-600 mt-0.5 tracking-normal">INCI-normalized · AI safety research</p>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left min-w-[440px]">
                    <thead>
                      <tr className="border-b border-white/6">
                        {['Ingredient', 'Role', 'Risk', 'Confidence'].map((h) => (
                          <th key={h} className="px-5 py-3 text-[10px] font-mono text-zinc-600 uppercase tracking-widest">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {result.ingredients.map((ing, i) => (
                        <motion.tr
                          key={i}
                          initial={{ opacity: 0 }}
                          animate={{ opacity: 1 }}
                          transition={{ delay: i * 0.05 }}
                          className="border-b border-white/5 last:border-0 hover:bg-white/4 transition-colors"
                        >
                          <td className="px-5 py-3 text-sm font-semibold text-white">{ing.name}</td>
                          <td className="px-5 py-3 text-xs font-mono text-zinc-500">{ing.role}</td>
                          <td className="px-5 py-3"><RiskBadge risk={ing.risk} /></td>
                          <td className={`px-5 py-3 text-sm font-bold font-mono ${
                            ing.confidence === 'High' ? 'text-emerald-400'
                            : ing.confidence === 'Medium' ? 'text-amber-400'
                            : 'text-zinc-500'
                          }`}>
                            {ing.confidence}
                          </td>
                        </motion.tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between px-6 py-4 border-b border-white/6 gap-3">
                  <div>
                    <h3 className="text-sm font-bold text-white uppercase tracking-tight">Full Report</h3>
                    <span className="text-[10px] font-mono text-zinc-600">AI-generated markdown</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => downloadFile(result.report, 'safety_report.md', 'text/markdown')}
                      className="flex items-center gap-1.5 bg-white/8 hover:bg-white/12 border border-white/10 text-white text-xs px-3 py-1.5 rounded-full font-mono transition-colors"
                    >
                      <FileText className="w-3 h-3" /> .md
                    </button>
                    <button
                      onClick={() => downloadFile(JSON.stringify(result, null, 2), 'safety_report.json', 'application/json')}
                      className="flex items-center gap-1.5 bg-white/8 hover:bg-white/12 border border-white/10 text-white text-xs px-3 py-1.5 rounded-full font-mono transition-colors"
                    >
                      <FileCode className="w-3 h-3" /> .json
                    </button>
                    <button
                      onClick={() => downloadFile(result.report, 'safety_report.txt', 'text/plain')}
                      className="flex items-center gap-1.5 bg-white text-black text-xs px-4 py-1.5 rounded-full font-bold transition-colors hover:bg-zinc-200"
                    >
                      <Download className="w-3 h-3" /> Export
                    </button>
                  </div>
                </div>
                <pre className="p-6 text-[11px] font-mono text-zinc-400 leading-relaxed tracking-normal whitespace-pre-wrap max-h-64 overflow-y-auto bg-black/40">
                  {result.report}
                </pre>
              </div>
            </motion.section>
          )}
        </AnimatePresence>
      </main>

      <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-30">
        <Dock className="items-end pb-3 gap-2">
          <DockItem
            onClick={onBackToLanding}
            className="bg-zinc-800/80 dark:bg-zinc-800 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>Home</DockLabel>
            <DockIcon>
              <ArrowLeft className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>

          <div className="w-px h-8 bg-white/10 self-center mx-1" />

          <DockItem
            onClick={() => setModal('about')}
            className="bg-zinc-800/80 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>About</DockLabel>
            <DockIcon>
              <ScrollText className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>

          <DockItem
            onClick={() => setModal('contact')}
            className="bg-zinc-800/80 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>Contact Info</DockLabel>
            <DockIcon>
              <Mail className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>

          <DockItem
            href="https://github.com/pritamdey0/IngredientSight-AI.git"
            className="bg-zinc-800/80 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>GitHub</DockLabel>
            <DockIcon>
              <Github className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>
        </Dock>
      </div>

      <Modal type={modal} onClose={() => setModal(null)} />
    </div>
  );
};

export default Dashboard;
