import React, { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Upload,
  ScrollText,
  Mail,
  X,
  Github,
  Sparkles,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Download,
  FileCode,
  Eye,
  FlaskConical,
  Shield,
  ArrowLeft,
} from 'lucide-react';

import { TextRoll } from '@/components/core/text-roll';
import { Spotlight } from '@/components/core/spotlight';
import { Dock, DockIcon, DockItem, DockLabel } from '@/components/core/dock';

// ─── Types ─────────────────────────────────────────────────────────────────

interface IngredientRow {
  name: string;
  risk: 'safe' | 'caution' | 'hazard';
  role: string;
  ewg: number;
}

interface AnalysisResult {
  productName: string;
  safetyScore: number;
  riskLabel: string;
  ingredientCount: number;
  ocrConfidence: number;
  summary: string;
  warnings: string[];
  ingredients: IngredientRow[];
  report: string;
}

type ModalType = 'about' | 'contact' | null;
type PipelineStep = 0 | 1 | 2 | 3 | 4 | 5;

// ─── Simulated analysis result ────────────────────────────────────────────

const buildResult = (name: string): AnalysisResult => ({
  productName: name,
  safetyScore: 86,
  riskLabel: 'Low Risk',
  ingredientCount: 33,
  ocrConfidence: 98,
  summary:
    'Well-balanced rinse-off formulation. Key actives (Panthenol, Histidine) show measurable breakage reduction in peer-reviewed literature. Preservative load within EU Annex V compliance. One sensitization vector: undisclosed Fragrance constituents.',
  warnings: [
    'Fragrance (Parfum) — undisclosed allergen potential, relevant for atopic skin.',
    'Sodium Laureth Sulfate — mild lipid-barrier depletion with prolonged high-frequency use.',
  ],
  ingredients: [
    { name: 'Water (Aqua)', risk: 'safe', role: 'Solvent', ewg: 1 },
    { name: 'Glycerin', risk: 'safe', role: 'Humectant', ewg: 1 },
    { name: 'Sodium Laureth Sulfate', risk: 'caution', role: 'Surfactant', ewg: 3 },
    { name: 'Cocamidopropyl Betaine', risk: 'safe', role: 'Co-surfactant', ewg: 2 },
    { name: 'Panthenol', risk: 'safe', role: 'Hair Fortifying', ewg: 1 },
    { name: 'Histidine', risk: 'safe', role: 'Chelating Agent', ewg: 1 },
    { name: 'Fragrance (Parfum)', risk: 'caution', role: 'Aromatic', ewg: 4 },
    { name: 'Methylisothiazolinone', risk: 'hazard', role: 'Preservative', ewg: 7 },
  ],
  report: `# IngredientSight AI — Safety Report\n\n**Product:** ${name}\n**Safety Index:** 86 / 100  ·  **Risk Level:** Low Risk\n\n---\n\n## Executive Summary\n\nWell-balanced rinse-off formulation. Primary surfactant system (SLES + CAPB) complemented by strengthening actives — Panthenol and Histidine — at concentrations shown to measurably reduce breakage. Preservative load within EU Annex V compliance.\n\n## Key Ingredients\n\n| Ingredient | Risk | EWG |\n|---|---|---|\n| Water (Aqua) | ✅ Safe | 1 |\n| Glycerin | ✅ Safe | 1 |\n| Panthenol | ✅ Safe | 1 |\n| Sodium Laureth Sulfate | ⚠️ Caution | 3 |\n| Fragrance | ⚠️ Caution | 4 |\n| Methylisothiazolinone | 🔴 Hazard | 7 |\n\n## Recommendations\n\n1. Safe for daily rinse-off use for the general population.\n2. Atopic skin types: perform patch test before regular use.\n3. Rinse thoroughly to minimise surfactant residue.\n\n---\n*Generated by IngredientSight AI · Multi-Agent LangGraph Pipeline v1.0*`,
});

// ─── Pipeline steps ───────────────────────────────────────────────────────

const PIPELINE_STEPS = [
  { id: 1, label: 'Upload', runMsg: 'Reading image…', doneMsg: '✓ Received' },
  { id: 2, label: 'OCR', runMsg: 'Extracting text…', doneMsg: '✓ 33 tokens' },
  { id: 3, label: 'INCI', runMsg: 'Normalising…', doneMsg: '✓ Mapped' },
  { id: 4, label: 'Research', runMsg: 'PubMed query…', doneMsg: '✓ 152 papers' },
  { id: 5, label: 'Safety', runMsg: 'EWG scoring…', doneMsg: '✓ Score: 86' },
];

// ─── Risk badge ────────────────────────────────────────────────────────────

const RiskBadge: React.FC<{ risk: IngredientRow['risk'] }> = ({ risk }) => {
  const cls = {
    safe: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/25',
    caution: 'bg-amber-500/10 text-amber-400 border-amber-500/25',
    hazard: 'bg-rose-500/10 text-rose-400 border-rose-500/25',
  }[risk];
  return (
    <span className={`text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded-full border ${cls}`}>
      {risk}
    </span>
  );
};

// ─── Modal ────────────────────────────────────────────────────────────────

const Modal: React.FC<{ type: ModalType; onClose: () => void }> = ({ type, onClose }) => (
  <AnimatePresence>
    {type && (
      <>
        <motion.div
          className="fixed inset-0 z-50 bg-black/60 backdrop-blur-md"
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
          onClick={onClose}
        />
        <motion.div
          className="fixed z-50 left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-sm bg-zinc-950 border border-white/10 rounded-3xl p-8 shadow-2xl"
          initial={{ opacity: 0, scale: 0.9, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.9, y: 10 }}
          transition={{ type: 'spring', stiffness: 340, damping: 30 }}
        >
          <button
            onClick={onClose}
            className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-white/8 text-zinc-500 hover:text-white transition-colors"
          >
            <X className="w-4 h-4" />
          </button>

          {type === 'about' ? (
            <div className="text-center space-y-4">
              <div className="w-14 h-14 rounded-2xl bg-white/8 border border-white/10 flex items-center justify-center mx-auto text-2xl">
                🧪
              </div>
              <div>
                <h3 className="text-lg font-bold text-white uppercase tracking-tight">IngredientSight AI</h3>
                <span className="text-[11px] font-mono text-zinc-500 block mt-1">AI Product Safety Platform</span>
              </div>
              <div className="space-y-2 text-sm text-zinc-400 text-center">
                <p className="bg-white/5 border border-white/8 rounded-xl px-4 py-2 font-mono text-xs">Version 1.0.0 — LangGraph v1.0</p>
                <p className="text-base">Made with <span className="text-red-400 text-lg">❤️</span> for safer cosmetics.</p>
              </div>
              <div className="text-[10px] font-mono text-zinc-600 pt-2">
                Powered by LangGraph · LangChain · Google Gemini
              </div>
            </div>
          ) : (
            <div className="space-y-5">
              <div>
                <h3 className="text-lg font-bold text-white uppercase tracking-tight">Contact Info</h3>
                <span className="text-[11px] font-mono text-zinc-500">Reach out or explore the project</span>
              </div>

              <div className="space-y-3">
                <div className="flex items-center gap-3 bg-white/5 border border-white/8 rounded-2xl p-4">
                  <div className="w-9 h-9 rounded-xl bg-white/8 flex items-center justify-center flex-shrink-0">
                    <Mail className="w-4 h-4 text-zinc-300" />
                  </div>
                  <div>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase block">Email</span>
                    <span className="text-sm text-white font-mono">asd@gmail.com</span>
                  </div>
                </div>

                <a
                  href="https://github.com/pritamdey0/IngredientSight-AI.git"
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-3 bg-white/5 border border-white/8 hover:border-white/20 rounded-2xl p-4 transition-colors group"
                >
                  <div className="w-9 h-9 rounded-xl bg-white/8 flex items-center justify-center flex-shrink-0">
                    <Github className="w-4 h-4 text-zinc-300" />
                  </div>
                  <div>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase block">GitHub Repository</span>
                    <span className="text-xs text-white font-mono group-hover:underline">IngredientSight-AI</span>
                  </div>
                </a>
              </div>
            </div>
          )}
        </motion.div>
      </>
    )}
  </AnimatePresence>
);

// ─── Dashboard ────────────────────────────────────────────────────────────

interface DashboardProps {
  onBackToLanding: () => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ onBackToLanding }) => {
  const [modal, setModal] = useState<ModalType>(null);
  const [dragOver, setDragOver] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [pipelineStep, setPipelineStep] = useState<PipelineStep>(0);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [productInput, setProductInput] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const runAnalysis = useCallback((name: string) => {
    setResult(null);
    setIsAnalyzing(true);
    setPipelineStep(0);

    let step: PipelineStep = 1;
    const tick = () => {
      setPipelineStep(step as PipelineStep);
      if (step < 5) {
        step = (step + 1) as PipelineStep;
        setTimeout(tick, 800);
      } else {
        setTimeout(() => {
          setIsAnalyzing(false);
          setResult(buildResult(name));
          setPipelineStep(0);
        }, 800);
      }
    };
    setTimeout(tick, 200);
  }, []);

  const handleFile = (file: File) => runAnalysis(file.name);

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer.files?.[0]) handleFile(e.dataTransfer.files[0]);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const val = productInput.trim();
    if (!val) return;
    setProductInput('');
    runAnalysis(val);
  };

  const scoreColor = result
    ? result.safetyScore >= 80 ? 'text-emerald-400' : result.safetyScore >= 60 ? 'text-amber-400' : 'text-rose-400'
    : '';

  return (
    <div className="relative min-h-screen bg-black text-white font-['Inter_Tight',sans-serif] font-medium tracking-[-0.04em] flex flex-col overflow-x-hidden">

      {/* ── GRID + SPOTLIGHT BACKGROUND ─────────────────────────────── */}
      <div className="pointer-events-none fixed inset-0 z-0">
        {/* Grid */}
        <svg className="absolute inset-0 h-full w-full opacity-20">
          <defs>
            <pattern id="dash-grid" width="40" height="40" patternUnits="userSpaceOnUse">
              <path d="M0 20H20M20 20V0M20 20H40M20 20V40" stroke="white" strokeOpacity="0.15" strokeWidth="0.5" />
              <rect x="19" y="19" width="2" height="2" fill="white" fillOpacity="0.12" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#dash-grid)" />
        </svg>

        {/* Blue radial pulse in upper-center */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[340px] bg-[radial-gradient(ellipse_at_top,rgba(59,130,246,0.18)_0%,transparent_70%)]" />

        {/* Subtle vignette */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,transparent_50%,rgba(0,0,0,0.6)_100%)]" />
      </div>

      {/* ── BACK BUTTON ─────────────────────────────────────────────── */}
      <div className="relative z-10 px-6 pt-5">
        <button
          onClick={onBackToLanding}
          className="flex items-center gap-2 text-[11px] font-mono text-zinc-600 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Landing Page
        </button>
      </div>

      {/* ── HEADING BANNER ─────────────────────────────────────────── */}
      <div className="relative z-10 flex flex-col items-center pt-10 pb-6 px-6 text-center">
        <motion.span
          initial={{ opacity: 0, y: -12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-[10px] font-mono text-zinc-500 uppercase tracking-[0.2em] mb-4 block"
        >
          AI-Powered Cosmetic Safety Platform
        </motion.span>

        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-[-0.05em] leading-none">
          <TextRoll className="text-white">IngredientSight AI</TextRoll>
        </h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1, duration: 0.6 }}
          className="mt-4 text-sm text-zinc-500 font-mono tracking-normal max-w-md"
        >
          Upload a product label or enter a product name — the AI does the rest.
        </motion.p>
      </div>

      {/* ── MAIN CONTENT ─────────────────────────────────────────────── */}
      <main className="relative z-10 flex-1 w-full max-w-4xl mx-auto px-5 pb-36 space-y-6">

        {/* ── UPLOAD SECTION ──────────────────────────────────────── */}
        <motion.section
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
          className="relative rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden"
        >
          {/* Section spotlight */}
          <Spotlight
            className="from-blue-700 via-blue-500 to-transparent blur-2xl"
            size={260}
          />

          <div className="relative z-10 p-6 sm:p-8">
            <div className="flex items-center gap-2 mb-6">
              <Upload className="w-4 h-4 text-zinc-400" />
              <span className="text-[11px] font-mono text-zinc-400 uppercase tracking-widest">Upload &amp; Analyze</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Drop zone */}
              <motion.div
                onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
                onDragLeave={() => setDragOver(false)}
                onDrop={handleDrop}
                onClick={() => fileRef.current?.click()}
                animate={{ borderColor: dragOver ? 'rgba(255,255,255,0.35)' : 'rgba(255,255,255,0.08)' }}
                className="relative cursor-pointer rounded-2xl border border-white/8 bg-white/5 p-8 flex flex-col items-center justify-center text-center gap-3 group hover:border-white/20 hover:bg-white/[0.07] transition-colors"
              >
                <input
                  ref={fileRef}
                  type="file"
                  accept="image/png,image/jpeg,image/jpg"
                  onChange={(e) => { if (e.target.files?.[0]) handleFile(e.target.files[0]); }}
                  className="hidden"
                />

                <div className="w-12 h-12 rounded-2xl bg-white/8 border border-white/10 flex items-center justify-center group-hover:scale-110 transition-transform text-white">
                  <Upload className="w-5 h-5" />
                </div>

                <div>
                  <p className="text-sm font-semibold text-white uppercase tracking-tight">Drop Image Here</p>
                  <p className="text-[11px] text-zinc-600 font-mono mt-1 tracking-normal">or click to browse · PNG · JPG · JPEG</p>
                </div>

                {dragOver && (
                  <motion.div
                    initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                    className="absolute inset-0 rounded-2xl bg-blue-500/10 border-2 border-blue-400/40 flex items-center justify-center"
                  >
                    <span className="text-sm font-bold text-blue-300">Release to analyze</span>
                  </motion.div>
                )}
              </motion.div>

              {/* Text input */}
              <form onSubmit={handleSubmit} className="rounded-2xl border border-white/8 bg-white/5 p-6 flex flex-col justify-between gap-4 hover:border-white/16 transition-colors">
                <div>
                  <p className="text-sm font-semibold text-white uppercase tracking-tight mb-1">Type Product Name</p>
                  <p className="text-[11px] text-zinc-600 font-mono tracking-normal">Analyze any cosmetic product by name.</p>
                </div>
                <div className="space-y-3">
                  <input
                    type="text"
                    value={productInput}
                    onChange={(e) => setProductInput(e.target.value)}
                    placeholder="e.g. Pantene Pro-V Shampoo"
                    className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-white/30 transition-colors font-mono tracking-normal"
                  />
                  <button
                    type="submit"
                    disabled={isAnalyzing}
                    className="w-full bg-white text-black py-2.5 rounded-full text-[12px] font-bold uppercase tracking-tight hover:bg-zinc-100 disabled:opacity-40 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
                  >
                    <Sparkles className="w-3.5 h-3.5" />
                    Run Analysis
                  </button>
                </div>
              </form>
            </div>

            {/* Pipeline animation (shown during analysis) */}
            <AnimatePresence>
              {isAnalyzing && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-5 overflow-hidden"
                >
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest">Multi-agent pipeline</span>
                    <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-ping" />
                  </div>
                  <div className="grid grid-cols-5 gap-2">
                    {PIPELINE_STEPS.map((step) => {
                      const done = pipelineStep > step.id;
                      const active = pipelineStep === step.id;
                      return (
                        <div
                          key={step.id}
                          className={`relative rounded-xl border p-3 overflow-hidden transition-all ${
                            done ? 'border-emerald-500/30 bg-emerald-500/5'
                                 : active ? 'border-blue-400/40 bg-blue-500/5'
                                 : 'border-white/6 bg-transparent'
                          }`}
                        >
                          <p className="text-[10px] font-bold text-white uppercase tracking-tight">{step.label}</p>
                          <p className="text-[9px] font-mono text-zinc-600 mt-0.5 leading-snug">
                            {done ? step.doneMsg : active ? step.runMsg : 'waiting'}
                          </p>
                          {active && (
                            <motion.div
                              className="absolute bottom-0 left-0 right-0 h-[2px] bg-blue-400"
                              initial={{ scaleX: 0 }} animate={{ scaleX: 1 }}
                              transition={{ duration: 0.8, ease: 'linear' }}
                              style={{ transformOrigin: 'left' }}
                            />
                          )}
                          {done && (
                            <CheckCircle2 className="absolute top-2 right-2 w-3 h-3 text-emerald-400" />
                          )}
                        </div>
                      );
                    })}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </motion.section>

        {/* ── RESULT SECTION ───────────────────────────────────────── */}
        <AnimatePresence>
          {result && (
            <motion.section
              initial={{ opacity: 0, y: 32 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 16 }}
              transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
              className="space-y-4"
            >
              {/* Section label */}
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-zinc-500" />
                <span className="text-[11px] font-mono text-zinc-500 uppercase tracking-widest">Analysis Report</span>
              </div>

              {/* Score header card */}
              <div className="relative rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden p-6 sm:p-8">
                <Spotlight className="from-emerald-700 via-emerald-500 to-transparent blur-2xl" size={240} />
                <div className="relative z-10 flex flex-col sm:flex-row sm:items-center justify-between gap-5">
                  <div>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest block mb-1">Analyzed Product</span>
                    <h2 className="text-2xl sm:text-3xl font-bold text-white uppercase tracking-tight leading-tight">
                      {result.productName}
                    </h2>
                    <p className="text-xs text-zinc-500 font-mono tracking-normal mt-2 max-w-md leading-relaxed">
                      {result.summary}
                    </p>
                  </div>
                  <div className="flex flex-col items-center sm:items-end gap-1 flex-shrink-0">
                    <span className={`text-6xl font-bold ${scoreColor}`}>{result.safetyScore}</span>
                    <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest">/ 100</span>
                    <span className={`text-xs font-bold uppercase px-3 py-1 rounded-full border mt-1 ${
                      result.safetyScore >= 80 ? 'text-emerald-400 bg-emerald-500/10 border-emerald-500/25'
                      : result.safetyScore >= 60 ? 'text-amber-400 bg-amber-500/10 border-amber-500/25'
                      : 'text-rose-400 bg-rose-500/10 border-rose-500/25'
                    }`}>{result.riskLabel}</span>
                  </div>
                </div>
              </div>

              {/* Stats row */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                  { label: 'Safety Score', value: `${result.safetyScore}/100`, color: scoreColor },
                  { label: 'Risk Level', value: result.riskLabel, color: 'text-white' },
                  { label: 'Ingredients', value: `${result.ingredientCount}`, color: 'text-white' },
                  { label: 'OCR Confidence', value: `${result.ocrConfidence}%`, color: 'text-blue-400' },
                ].map(({ label, value, color }) => (
                  <div key={label} className="rounded-2xl border border-white/8 bg-white/[0.025] p-4 flex flex-col gap-1">
                    <span className="text-[10px] font-mono text-zinc-600 uppercase tracking-widest">{label}</span>
                    <span className={`text-xl font-bold ${color}`}>{value}</span>
                  </div>
                ))}
              </div>

              {/* Warnings */}
              {result.warnings.length > 0 && (
                <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5">
                  <div className="flex items-center gap-2 mb-3">
                    <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
                    <span className="text-[10px] font-mono text-amber-400 uppercase tracking-widest">Warnings</span>
                  </div>
                  <ul className="space-y-2">
                    {result.warnings.map((w, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-xs text-zinc-300 leading-relaxed font-mono tracking-normal">
                        <span className="w-1.5 h-1.5 bg-amber-400 rounded-full mt-1.5 flex-shrink-0" />
                        {w}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Ingredient table */}
              <div className="rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden">
                <div className="px-6 py-4 border-b border-white/6">
                  <h3 className="text-sm font-bold text-white uppercase tracking-tight">Ingredient Breakdown</h3>
                  <p className="text-[10px] font-mono text-zinc-600 mt-0.5 tracking-normal">INCI-normalized · EWG hazard scoring</p>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left min-w-[440px]">
                    <thead>
                      <tr className="border-b border-white/6">
                        {['Ingredient', 'Role', 'Risk', 'EWG'].map((h) => (
                          <th key={h} className="px-5 py-3 text-[10px] font-mono text-zinc-600 uppercase tracking-widest">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {result.ingredients.map((ing, i) => (
                        <motion.tr
                          key={i}
                          initial={{ opacity: 0 }}
                          animate={{ opacity: 1 }}
                          transition={{ delay: i * 0.05 }}
                          className="border-b border-white/5 last:border-0 hover:bg-white/4 transition-colors"
                        >
                          <td className="px-5 py-3 text-sm font-semibold text-white">{ing.name}</td>
                          <td className="px-5 py-3 text-xs font-mono text-zinc-500">{ing.role}</td>
                          <td className="px-5 py-3"><RiskBadge risk={ing.risk} /></td>
                          <td className={`px-5 py-3 text-sm font-bold font-mono ${ing.ewg <= 2 ? 'text-emerald-400' : ing.ewg <= 4 ? 'text-amber-400' : 'text-rose-400'}`}>
                            {ing.ewg}
                          </td>
                        </motion.tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Report viewer + downloads */}
              <div className="rounded-3xl border border-white/8 bg-white/[0.025] overflow-hidden">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between px-6 py-4 border-b border-white/6 gap-3">
                  <div>
                    <h3 className="text-sm font-bold text-white uppercase tracking-tight">Full Report</h3>
                    <span className="text-[10px] font-mono text-zinc-600">AI-generated markdown</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => downloadFile(result.report, 'safety_report.md', 'text/markdown')}
                      className="flex items-center gap-1.5 bg-white/8 hover:bg-white/12 border border-white/10 text-white text-xs px-3 py-1.5 rounded-full font-mono transition-colors"
                    >
                      <FileText className="w-3 h-3" /> .md
                    </button>
                    <button
                      onClick={() => downloadFile(JSON.stringify(result, null, 2), 'safety_report.json', 'application/json')}
                      className="flex items-center gap-1.5 bg-white/8 hover:bg-white/12 border border-white/10 text-white text-xs px-3 py-1.5 rounded-full font-mono transition-colors"
                    >
                      <FileCode className="w-3 h-3" /> .json
                    </button>
                    <button
                      onClick={() => downloadFile(result.report, 'safety_report.txt', 'text/plain')}
                      className="flex items-center gap-1.5 bg-white text-black text-xs px-4 py-1.5 rounded-full font-bold transition-colors hover:bg-zinc-200"
                    >
                      <Download className="w-3 h-3" /> Export
                    </button>
                  </div>
                </div>
                <pre className="p-6 text-[11px] font-mono text-zinc-400 leading-relaxed tracking-normal whitespace-pre-wrap max-h-64 overflow-y-auto bg-black/40">
                  {result.report}
                </pre>
              </div>
            </motion.section>
          )}
        </AnimatePresence>
      </main>

      {/* ── APPLE DOCK (fixed bottom) ────────────────────────────────── */}
      <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-30">
        <Dock className="items-end pb-3 gap-2">
          {/* Home */}
          <DockItem
            onClick={onBackToLanding}
            className="bg-zinc-800/80 dark:bg-zinc-800 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>Home</DockLabel>
            <DockIcon>
              <ArrowLeft className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>

          {/* Divider */}
          <div className="w-px h-8 bg-white/10 self-center mx-1" />

          {/* About */}
          <DockItem
            onClick={() => setModal('about')}
            className="bg-zinc-800/80 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>About</DockLabel>
            <DockIcon>
              <ScrollText className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>

          {/* Contact */}
          <DockItem
            onClick={() => setModal('contact')}
            className="bg-zinc-800/80 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>Contact Info</DockLabel>
            <DockIcon>
              <Mail className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>

          {/* GitHub */}
          <DockItem
            href="https://github.com/pritamdey0/IngredientSight-AI.git"
            className="bg-zinc-800/80 hover:bg-zinc-700 transition-colors"
          >
            <DockLabel>GitHub</DockLabel>
            <DockIcon>
              <Github className="w-1/2 h-1/2 text-zinc-300" />
            </DockIcon>
          </DockItem>
        </Dock>
      </div>

      {/* ── MODAL ───────────────────────────────────────────────────── */}
      <Modal type={modal} onClose={() => setModal(null)} />
    </div>
  );
};

export default Dashboard;
